version: '3'
services:
  rabbit-server:
    hostname: rabbit-server
    image: rabbitmq:management-alpine
    container_name: rabbit-server
    ports:
      # 端口
      - "5672:5672"
      # web端口
      - "15672:15672"
    environment:
      # 配置账户/密码
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin